### ISSUE TITLE
I don't see "advanced options" or "import a list"?

### ISSUE THREAD

**Issue by gingerbeardman** [HackPotter/ListOfPromotedTweets#1]
You say: Twitter > Settings and Privacy > Blocked Accounts > Advanced Options > Import a List

I have to go: Twitter > Settings and Privacy > Content Preferences > Blocked Accounts
And I do not see "Advanced Options"?

![Screen shot 2019-05-27 at 13 21 53](https://user-images.githubusercontent.com/49612/58419400-6c255300-8082-11e9-87ad-3b0cc0c09ffd.png)

**Comment by transkatgirl** [comment]
You have to use the desktop Twitter client to import a list. mobile.twitter.com doesn't have that functionality.

**Comment by gingerbeardman** [comment]
I'm using desktop, but it appears to be "new twitter"?

https://www.theverge.com/2019/1/22/18193322/twitter-desktop-update-emoji-trending-search

**Comment by transkatgirl** [comment]
Idk, try following Twitter's guide on how to import a blocklist?
https://help.twitter.com/en/using-twitter/advanced-twitter-block-options

**Comment by gingerbeardman** [comment]
I've reached out to twitter to see when they are bringing this feature back to "new" twitter. Thanks!
